---

- hosts: all
  vars:
    user: horni

  tasks:

  - name: create user 
    user:
      name: "{{ user }}"
      shell: /bin/bash
      groups: wheel
      append: yes

  - name: allow passwordless sudo
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
  
  - name: set ssh key for user
    authorized_key:
      user: "{{ user }}"
      state: present
      key: https://github.com/horni23.keys

  - name: set ssh key for root
    authorized_key:
      user: root
      state: present
      key: https://github.com/horni23.keys

  - name: setup cockpit
    yum:
      name: cockpit
      state: latest
  
  - name: run cockpit persistently
    systemd: 
      name: cockpit
      enabled: yes
      state: started

  - name: setup visual studio code rpm key
    rpm_key:
      state: present
      key: https://packages.microsoft.com/keys/microsoft.asc

  - name: setup visual studio code repo
    yum_repository:
      name: code
      description: Visual Studio Code Repo
      baseurl: https://packages.microsoft.com/yumrepos/vscode
      gpgcheck: yes
      gpgkey: https://packages.microsoft.com/keys/microsoft.asc

  - name: setup EPEL
    yum:
      name: epel-release
      state: latest

  - name: install visual studio code
    yum:
      name: code
      update_cache: yes
      state: latest

  - name: install git
    yum:
      name: git
      state: latest
  
  - name: install pip3
    yum:
      name: python3-pip
      state: latest

  - name: install ansible
    yum:
      name: ansible
      enablerepo: epel-playground
      state: latest

  - name: create directory for host configuration
    file:
      path: /home/{{ user }}/ansible-centos8-conf/
      state: directory

  - name: setup git repo for host configuration
    git:
      repo: 'https://github.com/horni23/ansible-centos8-conf.git'
      dest: /home/{{ user }}/ansible-centos8-conf/
