---

# this playbook is for configuring a CentOS 8 host remotely first
# after the initial run futher configuration can be done locally on the CentOS 8 host itself

- hosts: all
  vars:
    user: horni
    hostname: centy

  tasks:

  - name: set hostname
    hostname:
      name: "{{ hostname }}"

  - name: create user 
    user:
      name: "{{ user }}"
      shell: /bin/bash
      groups: wheel
      append: yes

  - name: allow passwordless sudo
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
  
  - name: set ssh key for user
    authorized_key:
      user: "{{ user }}"
      state: present
      key: https://github.com/horni23.keys

  - name: set ssh key for root
    authorized_key:
      user: root
      state: present
      key: https://github.com/horni23.keys

  - name: setup visual studio code rpm key
    rpm_key:
      state: present
      key: https://packages.microsoft.com/keys/microsoft.asc

  - name: setup visual studio code repo
    yum_repository:
      name: code
      description: Visual Studio Code Repo
      baseurl: https://packages.microsoft.com/yumrepos/vscode
      gpgcheck: yes
      gpgkey: https://packages.microsoft.com/keys/microsoft.asc

  - name: setup EPEL
    yum:
      name: epel-release
      state: latest

  - name: install rpmfusion
    yum:
      name: 
        - https://download1.rpmfusion.org/free/el/rpmfusion-free-release-8.noarch.rpm 
        - https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-8.noarch.rpm
      state: present
  
  - name: install cockpit, steam, visual studio code, git, pip3, golang, ansible, vlc, tlp, gnome-tweaks
    yum:
      name:
        - cockpit
#       - steam
        - code
        - git
        - python3-pip
        - golang
        - ansible
        - vlc
        - tlp
        - gnome-tweaks
      update_cache: yes
      enablerepo: epel-playground
      state: latest

  - name: update all packages
    yum:
      name: '*'
      state: latest

  - name: create directory for host configuration
    file:
      path: /home/{{ user }}/ansible-centos8-conf/
      state: directory

  - name: setup git repo for host configuration
    git:
      repo: 'https://github.com/horni23/ansible-centos8-conf.git'
      dest: /home/{{ user }}/ansible-centos8-conf/

  - name: change permissions for git host config repo
    file:
      path: /home/{{ user }}/ansible-centos8-conf/
      owner: "{{ user }}"
      group: "{{ user }}"
      recurse: yes

  - name: generate ssh keys
    openssh_keypair: 
      path: /home/{{ user }}/.ssh/id_rsa
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: read own ssh pubkey
    command: cat /home/{{ user }}/.ssh/id_rsa.pub
    register: ssh_key
  
  - name: set own ssh key
    lineinfile:
      path: /home/{{ user }}/.ssh/authorized_keys
      line: "{{ ssh_key.stdout }}"

  - name: clone gnome-layout-manager
    git: 
      repo: 'https://github.com/horni23/gnome-layout-manager.git'
      dest: /home/{{ user }}/gnome-layout-manager

  - name: run gnome-layout-manager
    command: /home/{{ user }}/gnome-layout-manager/layoutmanager.sh --unity

  - name: clone bash_it
    git:
      repo: https://github.com/Bash-it/bash-it.git
      dest: /home/{{ user }}/.bash_it

  - name: run bash_it
    command: /home/{{ user }}/.bash_it/install.sh -s
    args:
      creates: /home/{{ user }}/.bashrc.bak

  - name: enable and start cockpit
    systemd: 
      name: cockpit
      enabled: yes
      state: started

